// src/components/git/languages/languages.component.ts
import { CommonModule, PercentPipe } from '@angular/common';
import { Component, computed, input } from '@angular/core';
import { ILanguages } from '../../../models/github-api/languages';
import { ILanguage } from '../../../models/language';
import { DEFAULT_COLOR as DEFAULT_LANGUAGE_COLOR, languageColors } from '../../../settings/languageColors';
import { MathExt } from '../../../../repos/common/library/math';

@Component({
  selector: 'app-languages',
  standalone: true,
  imports: [
    CommonModule,
    PercentPipe,
  ],
  templateUrl: './languages.component.html',
  styleUrl: './languages.component.scss',
})
export class LanguagesComponent {
  languages = input.required<ILanguages | null>();
  mappedLanguages = computed(() => {
    var languages = this.languages();
    if (languages === null) {
      return [];
    }
    var maxValue = MathExt.sum(Object.values(languages));
    var mappedLanguages: ILanguage[] = Object.keys(languages).map((language) => {
      var percentage = (languages![language] / maxValue);
      var colorString = languageColors[language] ?? DEFAULT_LANGUAGE_COLOR;
      return {
        name: language,
        percentage: percentage,
        color: colorString,
      }
    });
    return mappedLanguages;
  });

  getLanguageTooltip(language: ILanguage) {
    return `${language.name}: ${language.percentage.toPrecision(2)}%`;
  }

  getBackgroundColor(language: ILanguage) {
    return languageColors.hasOwnProperty(language.name) ? languageColors[language.name] : "#222222";
  }
}

@defer (on immediate; when languages() !== null) {
  <!-- <div class="margin"> -->
    <div class="mb-2">
      <div class="language-bar block">
        @for (language of mappedLanguages(); track $index) {
          <span
            [ngStyle]="{
              width: language.percentage * 100 + '%',
              backgroundColor: language.color,
            }"
            [title]="getLanguageTooltip(language)"
            class="project-card-language-bar"
          ></span>
        }
      </div>
    </div>
    <ul>
      @for (language of mappedLanguages(); track $index) {
        <li
          class="inline me-3 last-of-type:me-0 inline-flex justify-center items-center flex-nowrap"
        >
          <div
            class="octicon me-2"
            [ngStyle]="{ backgroundColor: getBackgroundColor(language) }"
          ></div>
          <span class="text-primary me-1">{{ language.name }}</span>
          <span class="text-secondary">{{
            language.percentage | percent: "0.0"
          }}</span>
        </li>
      }
    </ul>
  <!-- </div> -->
} @placeholder {
  <div class="text-slate-300 italic">Github languages</div>
} @loading {
  <div class="text-slate-300 italic">Loading</div>
} @error {
  <div class="text-slate-300 italic">Error fetching languages</div>
}

// dev/src/components/controllers/Languages.tsx
import { useTheme } from '@material-ui/core';
import { Typography } from '@material-ui/core';
import { useAsync } from 'react-async-hook';
import languageColors from 'config/languageColors.json';
import token from 'config/token.json';

const languageColors2: { [str: string]: string } = languageColors;

export interface IGithubRepo {
	repoName: string;
	repoOwner: string;
}

const fetchLanguages = async (repoName: string, repoOwner: string) =>
	(
		await fetch(`https://api.github.com/repos/${repoOwner}/${repoName}/languages`, {
			headers: {
				Authorization: `token ${'g' + token.readonlyToken.substring(2)}`
			}
		})
	).json();

export default function Languages(props: IGithubRepo) {
	const { repoName, repoOwner } = props;
	const languages = useAsync(fetchLanguages, [repoName, repoOwner]);
	const theme = useTheme();

	if (languages.loading) {
		return (
			<>
				<Typography color="textSecondary" style={{ fontStyle: 'italic' }}>
					Loading
				</Typography>
			</>
		);
	} else if (languages.error) {
		return (
			<>
				<Typography color="textSecondary" style={{ fontStyle: 'italic' }}>
					Error fetching languages
				</Typography>
			</>
		);
	} else if (languages.result.message !== undefined) {
		return (
			<>
				<Typography color="textSecondary" style={{ fontStyle: 'italic' }}>
					Repository: {languages.result.message}
				</Typography>
			</>
		);
	}

	const languageNames = Object.keys(languages.result);
	const maxvalue = sum(Object.values(languages.result));
	const percentages = Object.values<number>(languages.result).map((val: number) => (val === 0 ? 0 : (val / maxvalue) * 100));
	const percentagesStr = percentages.map((percentage: number) =>
		Math.log10(percentage) < 2 ? percentage.toPrecision(2) : percentage.toString()
	);

	const percentBars = (
		<div>
			<span className="project-card-progress">
				{percentages.map((percentage: number, index: number) => {
					var langName = languageNames[index];
					var backgroundColor = languageColors2.hasOwnProperty(langName) ? languageColors2[langName] : theme.palette.grey[400];
					return (
						<span
							key={index}
							style={{
								width: `${percentage}%`,
								backgroundColor: backgroundColor
							}}
							className="project-card-language-bar"
						/>
					);
				})}
			</span>
		</div>
	);

	const languageDots = (
		<ul className="project-card-languages-ul">
			{languageNames.map((name: string, index: number) => {
				var backgroundColor = languageColors2.hasOwnProperty(name) ? languageColors2[name] : theme.palette.grey[400];

				return (
					<li className="d-inline" key={index}>
						<div className="project-card-languages-chip flex-items-center d-inline-flex me-3">
							<div className="octicon" style={{ backgroundColor: backgroundColor }}></div>
							{/* <svg
								className="octicon me-2"
								fill={backgroundColor}
								viewBox="0 0 16 16"
								version="1.1"
								width="16"
								height="16"
								aria-hidden="true"
							>
								<path fillRule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8z"></path>
							</svg> */}
							<span className="pixel-font project-card-languages-name">{name}</span>
							<span className="pixel-font" style={{ color: theme.palette.grey[400] }}>
								{percentagesStr[index]}%
							</span>
						</div>
					</li>
				);
			})}
		</ul>
	);

	return (
		<>
			{percentBars}
			{languageDots}
		</>
	);
}

function sum(arr: number[]): number {
	var sum: number = 0;
	arr.forEach((value) => (sum += value));
	return sum;
}
