// src/components/git/project-card/project-card.component.ts
import { CommonModule } from '@angular/common';
import { Component, computed, input } from '@angular/core';
import { IProjectCard } from '../../../models/project-card';
import { LanguagesComponent } from '../languages/languages.component';
import { DatetimePipe } from '../../../pipes/datetime.pipe';
import { TimeFromNowPipe } from '../../../pipes/time-from-now.pipe';
import { AppSettingsService } from '../../../services/appsettings.service';

@Component({
  selector: 'app-project-card',
  standalone: true,
  imports: [
    CommonModule,
    LanguagesComponent,
    DatetimePipe,
    TimeFromNowPipe,
  ],
  templateUrl: 'project-card.component.html',
  // styleUrl: 'project-card.component.scss'
})
export class ProjectCardComponent {
  projectCard = input.required<IProjectCard>();
  index = input<number>(0);
  isEven = computed<boolean>(() => this.index() % 2 === 0);
  isOdd = computed<boolean>(() => this.index() % 2 !== 0);

  constructor(
    protected appSettings: AppSettingsService,
  ) {}
}

<div class="body">
  <div>
    <!-- Title, desc, etc -->
    <div class="flex items-center justify-between gap-3 margin text-primary">
      <div class="flex items-center gap-3">
        <!-- Title -->
        <h3 class="text-2xl font-semibold">
          <a [href]="projectCard().repo().html_url" target="_blank">
            <span class="text-slate-300 font-light"
              >{{ projectCard().repo().owner.login }}/</span
            ><span class="hover:underline hover:underline-offset-8">{{ projectCard().repo().name }}</span>
          </a>
        </h3>

        <!-- Owner gravatar -->
        <div
          class="rounded-full overflow-clip"
          [title]="projectCard().repo().owner.login"
        >
          <a [href]="projectCard().repo().owner.html_url" target="_blank">
            <img
              class="w-8 h-8"
              [src]="projectCard().repo().owner.avatar_url"
              alt="repo owner"
            />
          </a>
        </div>

        <!-- Repo flairs -->
        @if (projectCard().repo().fork) {
          <span class="font-light text-lg text-slate-300">fork</span>
        }
        @if (projectCard().repo().private) {
          <span class="font-light text-lg text-slate-300">private</span>
        }
      </div>

      <!-- Repo counts -->
      <div class="flex gap-3">
        <div class="chip bg-primary">
          {{ projectCard().repo().open_issues_count }} open issues 📝
        </div>
        <div class="chip bg-primary">
          {{ projectCard().repo().stargazers_count }} stars 🤩
        </div>
        <div class="chip bg-primary">
          {{ projectCard().repo().watchers_count }} watchers 👁
        </div>
      </div>
    </div>

    <div
      class="flex flex-wrap gap-3 font-light padded-x py-2 bg-secondary text-secondary"
    >
      <div>Created {{ projectCard().repo().created_at | TimeFromNow }} ago</div>
      <div class="border-r text-secondary"></div>
      <div>
        Last updated {{ projectCard().repo().updated_at | TimeFromNow }} ago
      </div>
    </div>

    @if (projectCard().repo().description) {
      <div class="margin text-primary">
        {{ projectCard().repo().description }}
      </div>
    }
  </div>

  @if (projectCard().repo().topics.length > 0) {
    <div class="chips margin">
      @for (chip of projectCard().repo().topics; track $index) {
        <div class="chip bg-primary text-primary">
          {{ chip }}
        </div>
      }
    </div>
  }

  <!-- Languages & Chips -->
  @if (appSettings.settings.features.languages) {
    @if (projectCard().repo().private) {
      <div class="italic text-primary chip">No language information</div>
    } @else {
      <div class="margin">
        <app-languages [languages]="projectCard().languages()" />
      </div>
    }
  }
</div>

<!-- Buttons -->
<!-- <div> -->
<!-- TODO: Add a disabled button with a disabled icon for when no actions are available -->
<!-- @for (iconButton of projectCard().iconButtons; track $index) {
      <a
        [href]="iconButton.href"
        rel="noreferrer"
        target="_blank"
        [matTooltip]="iconButton.title"
      >
        {{ iconButton.icon }}
      </div>
      </a>
    } -->
<!-- </div> -->

<!-- Image -->
<!-- @if (projectCard().image !== undefined) {
  <div class="image-container">
    <img
      [alt]="projectCard().image!.alt"
      [src]="projectCard().image!.url"
      [title]="projectCard().image!.title"
      class="image"
    />
  </div>
} -->
<!-- @else {
    <div
      class="image-container h-full flex items-center justify-center"
    >
      <div class="text-slate-300 text-center">No Image</div>
  </div>
} -->

// dev/src/components/controllers/ProjectCard.tsx
import { Chip, Tooltip } from '@material-ui/core';
import { CSSProperties } from 'react';
import Languages from './Languages';
import IfElse from './IfElse';

interface IProjectCard {
    isPrivate?: boolean;
    repo: IProjectCardRepo;
    name: string;
    subtitle?: string;
    chips: string[];
    desc: JSX.Element | string;
    image?: IProjectCardImage | IProjectCardImage[];
    imageStyle?: CSSProperties;
    iconButtons?: IProjectCardActionButton[];
}

interface IProjectCardImage {
    url: string;
    alt?: string;
    title?: string;
    imageFit?: 'fill' | 'contain' | 'cover' | 'none' | 'scale-down';
}

interface IProjectCardRepo {
    name: string;
    owner: string;
}

interface IProjectCardActionButton {
    title: React.ReactElement | string;
    icon: React.ReactElement;
    href: string;
}

export default function ProjectCard(props: IProjectCard) {
    const { repo, name, subtitle, chips, desc, isPrivate, image, imageStyle, iconButtons } = props;
    const _image = image && Array.isArray(image) ? image[0] : image;
    const cardPrefix = name + '-project-card-';

    return (
        <div className="project-card">
            {/* Title and Body */}
            <div
                id={cardPrefix + 'project-card-top'}
                className="project-card-top green-30-bg green-20-shadow d-flex justify-content-between"
            >
                <div id={cardPrefix + 'info'} className="project-card-info  h-100">
                    {/* Title */}
                    <div className="project-card-title green-35-bg green-20-shadow p-3">
                        <h3 id={cardPrefix + 'title'}>
                            {name}
                        </h3>
                        {/* Subtitle */}
                        {subtitle !== undefined && subtitle !== '' && (
                            <div id={cardPrefix + 'subtitle'} className="text-secondary">
                                {subtitle}
                            </div>
                        )}
                    </div>

                    <div className="p-3 h-100">
                        

                        {/* Desc */}
                        <div id={cardPrefix + 'body'} className="project-card-description">
                            {desc}
                        </div>
                    </div>
                </div>

                {/* Image */}
                {/* <div id={cardPrefix + 'image-wrapper'} className="project-card-image-wrapper"> */}
                <IfElse condition={_image !== undefined && _image.url !== ''}>
                    <img
                        id={cardPrefix + 'image'}
                        className="project-card-image green-35-bg green-20-border-left"
                        alt={_image?.alt}
                        src={_image?.url}
                        title={_image?.title}
                        style={imageStyle}
                    />
                    <div
                        id={cardPrefix + 'no-image'}
                        className="project-card-image green-35-bg green-20-border-left"
                        style={{
                            display: 'flex',
                            alignItems: 'center',
                            justifyContent: 'center'
                        }}
                    >
                        <div className="text-secondary text-center">
                            No Image
                        </div>
                    </div>
                </IfElse>
                {/* </div> */}
            </div>

            {/* Languages and Buttons*/}
            <div className="green-35-bg">
                <div id={cardPrefix + 'languages'} className="project-card-languages">
                    {/* Languages & Chips */}
                    <div id={cardPrefix + 'chips'} className="project-card-chips">
                        {chips.map((chip, index) => (
                            <Chip
                                key={index}
                                size="small"
                                label={chip}
                                className="project-card-chip"
                                style={{ color: 'white' }}
                            />
                        ))}
                    </div>
                    <IfElse condition={isPrivate === true}>
                        <div className="text-secondary">
                            Private repository
                        </div>
                        <Languages repoName={repo.name} repoOwner={repo.owner} />
                    </IfElse>
                </div>

                {/* Actions */}
                <div id={cardPrefix + 'action'} className="project-card-actions">
                    {/* TODO: Add a disabled button with a disabled icon for when no actions are available */}
                    {iconButtons !== undefined &&
                        iconButtons.map((iconButton, index) => (
                            <Tooltip key={index} title={iconButton.title} color="primary" arrow>
                                <a className="project-card-action py-2" href={iconButton.href} rel="noreferrer" target="_blank">
                                    {iconButton.icon}
                                </a>
                            </Tooltip>
                        ))}
                </div>
            </div>
        </div>
    );
}
