// src/app/star-graph/star-graph.component.ts
import { CommonModule } from '@angular/common';
import { Component, input, signal } from '@angular/core';
import { Graph, GraphEdge, GraphNode } from '../../models/graph';
import { StarSource } from '../../models/stars';

@Component({
  selector: 'app-star-graph',
  standalone: true,
  imports: [
    CommonModule,
  ],
  templateUrl: './star-graph.component.html',
})
export class StarGraphComponent {
  protected readonly img = StarSource.Star8x8;
  protected readonly radius = 4;
  protected readonly starWidth = this.radius * 2;
  protected readonly starHeight = this.radius * 2;
  protected readonly lineOpacity = 1;

  width = input.required<number>();
  height = input.required<number>();
  // TODO: replace number[][] type with FixedArray from ColorSlicer
  nodes = input.required<GraphNode[]>(); // x,y coords
  edges = input.required<GraphEdge[]>();
  graph = signal<Graph>(new Graph());

  ngOnInit() {
    this.graph.set(this.constructStarGraph(this.nodes(), this.edges()));
  }

  // Add the size of a star to the provided number
  offsetCoordinateToCenter(coord: number, radius: number) {
    return coord + radius;
  }

  constructStarGraph(nodes: GraphNode[], edges: GraphEdge[]): Graph {
    const graph = new Graph([], [])
    for (let i = 0; i < nodes.length; i++) {
      const node = nodes[i];
      graph.nodes.push(new GraphNode(
        this.offsetCoordinateToCenter(node.x, this.radius),
        this.offsetCoordinateToCenter(node.y, this.radius)
      ));
    }
    for (let i = 0; i < edges.length; i++) {
      const edge = edges[i];
      graph.edges.push(new GraphEdge(edge.node1, edge.node2));
    }
    return graph;
  }
}

<div>
  <svg [attr.width]="width()" [attr.height]="height()">
    @for (node of graph().nodes; track $index) {
      <image [attr.x]="node.x" [attr.y]="node.y" [attr.height]="starHeight" [attr.width]="starWidth" [attr.href]="img" />
    }
    @for (edge of graph().edges; track $index) {
      <line
        [attr.x1]="offsetCoordinateToCenter(edge.node1.x, radius)"
        [attr.y1]="offsetCoordinateToCenter(edge.node1.y, radius)"
        [attr.x2]="offsetCoordinateToCenter(edge.node2.x, radius)"
        [attr.y2]="offsetCoordinateToCenter(edge.node2.y, radius)"
        stroke="white"
        [attr.opacity]="lineOpacity" />
    }
  </svg>
</div>

// src/components/controllers/StarGraph.tsx
import { Graph, GraphEdge, GraphNode } from 'library/graph';
import { addPercentages, toPercentage } from 'library/percentages';

const img = 'images/star_8x8.png';
const radius = 4;
const starWidth = radius * 2;
const starHeight = radius * 2;
const lineOpacity = 1;

interface IStarGraph {
    coords: Array<Array<number | string>>; // x,y coords
    connections: number[][]; // node to node
    width: number;
    height: number;
}

export default function StarGraph(props: IStarGraph) {
    const { coords, connections, width, height } = props;
    const graph = constructStarGraph(coords, connections);
    const stars = [];
    const edges = [];
    const radiusWidthPercent = toPercentage(radius / width);
    const radiusHeightPercent = toPercentage(radius / height);
    for (var node of graph.nodes) {
        stars.push(<image x={node.x} y={node.y} height={starHeight} width={starWidth} href={img} />);
    }
    for (var edge of graph.edges) {
        var line1X = typeof edge.node1.x === 'string' ? addPercentages(edge.node1.x, radiusWidthPercent) : edge.node1.x;
        var line1Y = typeof edge.node1.y === 'string' ? addPercentages(edge.node1.y, radiusHeightPercent) : edge.node1.y;
        var line2X = typeof edge.node2.x === 'string' ? addPercentages(edge.node2.x, radiusWidthPercent) : edge.node2.x;
        var line2Y = typeof edge.node2.y === 'string' ? addPercentages(edge.node2.y, radiusHeightPercent) : edge.node2.y;
        edges.push(<line x1={a(line1X)} y1={a(line1Y)} x2={a(line2X)} y2={a(line2Y)} stroke="white" opacity={lineOpacity} />);
    }

    return (
        <div>
            <svg width={width} height={height}>
                {edges}
                {stars}
            </svg>
        </div>
    );
}

// Add the size of a star to the provided number
function a(num: number | string) {
    if (typeof num === 'string') {
        return num;
    }
    return num + radius;
}

function constructStarGraph(nodes: Array<Array<number | string>>, edges: number[][]): Graph {
    const graphNodes: Array<GraphNode> = [];
    const graphEdges: Array<GraphEdge> = [];
    for (let i = 0; i < nodes.length; i++) {
        const node = nodes[i];
        graphNodes.push({
            x: a(node[0]),
            y: a(node[1])
        });
    }
    for (let i = 0; i < edges.length; i++) {
        const edge = edges[i];
        graphEdges.push(new GraphEdge(graphNodes[edge[0]], graphNodes[edge[1]]));
    }
    return new Graph(graphNodes, graphEdges);
}
