// src/app/clouds/clouds.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { LARGEST_CLOUD_HEIGHT, TOP_OFFSET } from '../../models/clouds';
import { CloudComponent } from './cloud/cloud.component';

@Component({
  selector: 'app-clouds',
  standalone: true,
  imports: [
    CommonModule,
    CloudComponent
  ],
  templateUrl: './clouds.component.html',
})
export class CloudsComponent {
  TOP_OFFSET = TOP_OFFSET
  LARGEST_CLOUD_HEIGHT = LARGEST_CLOUD_HEIGHT
}

<div class="relative overflow-x-clip w-full" [ngStyle]="{ top: TOP_OFFSET, height: LARGEST_CLOUD_HEIGHT }">
  <!-- group 1 -->
  <app-cloud [cloudIndex]="0" [initialLeft]="-0.025" [top]="0" />
  <app-cloud [cloudIndex]="2" [initialLeft]="0.12"   [top]="0"    [distance]="1" />

  <!-- group 2 -->
  <app-cloud [cloudIndex]="1" [initialLeft]="0.31"   [top]="0.05" [distance]="0.7" />
  <app-cloud [cloudIndex]="2" [initialLeft]="0.4"    [top]="0" />
  <app-cloud [cloudIndex]="1" [initialLeft]="0.55"   [top]="0.05" [distance]="0.7" />

  <!-- group 3 -->
  <app-cloud [cloudIndex]="1" [initialLeft]="0.7"    [top]="0" />
  <app-cloud [cloudIndex]="0" [initialLeft]="0.85"   [top]="0.05" [distance]="0.5" />

  <!-- end cloud -->
  <app-cloud [cloudIndex]="0" [initialLeft]="0.975"  [top]="0" />

  <!-- Background clouds -->
  <app-cloud [cloudIndex]="3" [initialLeft]="0.05"   [top]="0"    [distance]="0.25" />
  <app-cloud [cloudIndex]="3" [initialLeft]="0.22"   [top]="0"    [distance]="0.4" />
  <app-cloud [cloudIndex]="3" [initialLeft]="0.45"   [top]="0"    [distance]="0.3" />
  <app-cloud [cloudIndex]="3" [initialLeft]="0.7"    [top]="0.05" [distance]="0.5" />

  <!-- end cloud -->
  <app-cloud [cloudIndex]="3" [initialLeft]="0.95"   [top]="0" />
</div>

// dev/src/components/views/Clouds.tsx
import Cloud, { TOP_OFFSET } from 'components/controllers/Cloud';

export default function Clouds({ id }: { id: string }) {
    // return null;
	return (
		<div id={id} className="clouds" style={{ top: TOP_OFFSET }}>
			{/* group 1 */}
			<Cloud cloudIndex={0} initialLeft={-0.025} top={0} />
			<Cloud cloudIndex={2} initialLeft={0.12}   top={0}    distance={1} />

			{/* group 2 */}
			<Cloud cloudIndex={1} initialLeft={0.31}   top={0.05} distance={0.7} />
			<Cloud cloudIndex={2} initialLeft={0.4}    top={0} />
			<Cloud cloudIndex={1} initialLeft={0.55}   top={0.05} distance={0.7} />

			{/* group 3 */}
			<Cloud cloudIndex={1} initialLeft={0.7}    top={0} />
			<Cloud cloudIndex={0} initialLeft={0.85}   top={0.05} distance={0.5} /> 
            distance
			{/* end cloud */}
			<Cloud cloudIndex={0} initialLeft={0.975}  top={0} />

			{/* Background clouds */}
			<Cloud cloudIndex={3} initialLeft={0.05}  top={0}     distance={0.25} />
			<Cloud cloudIndex={3} initialLeft={0.22}   top={0}    distance={0.4} />
			<Cloud cloudIndex={3} initialLeft={0.45}   top={0}    distance={0.3} />
			<Cloud cloudIndex={3} initialLeft={0.7}    top={0.05} distance={0.5} />

			{/* end cloud */}
			<Cloud cloudIndex={3} initialLeft={0.95}   top={0} />
		</div>
	);
}
